[redis]
host = "localhost"
port = 6379
db = 0
user = "usr"
password = "pwd"
redis_password = "super_password"

[postgres]
host = "localhost"
port = 5432
user = "usr"
password = "pwd"
db_name = "db"
ssl_mode = "disable"
migrations_path = "app/migrations"

[minio]
host = "localhost"
port = 9000
root_user = "minio"
root_password = "password"
articles_bucket = "articles"
attachments_bucket = "attachments"
avatars_bucket = "avatars"
use_ssl = false
url_lifetime = "24h"

[docker]
image_name = "alpine"
timeout = 5

[telegram]
information_url = ""
hello_message = [
  "*👨‍💻 Привет! Я бот поддержки*",
  "Я могу ответить на все ваши вопросы!",
  "*Напишите мне,* и я постараюсь помочь вам!",
]
error_message = "Если Вы не нашли ответа на свой вопрос или нуждаетесь в консультации наших технических специалистов, оставьте запрос для службы поддержки"
main_image = ""
main_buttons = [{ text = "✏️  Задать вопрос", data = "ask_question" }]
